server:
  port: 9090
spring:
  application.name: shareIt
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    username: dbuser
    password: 12345
    driverClassName: org.postgresql.Driver

